=== priamixdj/5AI/TPSIT/XML/ricetta/ricetta.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ricettario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ricetta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titolo" />
                            <xs:element name="autore" />
                            <xs:element name="ingredienti">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nome"/>
                                        <xs:element name="quantita"/>
                                        <xs:element name="unita" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="procedura">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="procedo" maxOccurs="unbounded" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>             
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== priamixdj/5AI/TPSIT/XML/ricetta/ricetta.xml
<?xml version="1.0" encoding="UTF-8"?>
<ricettario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ricetta.xsd"><ricetta>
    <titolo>Torta</titolo>
    <autore>Giacomini Giacomo</autore>
    <ingredienti>
        <nome>farina</nome>
        <quantita>3</quantita>
        <unita>3</unita>
    </ingredienti>
    <procedura>
        <procedo>verso la farina</procedo>
        <procedo>inserire l acqua</procedo>
        <procedo>prendere la prima unita </procedo>
        <procedo>mescolare</procedo>
    </procedura>
</ricetta>
<ricetta>
    <titolo>Torta</titolo>
    <autore>Giacomini Giacomo</autore>
    <ingredienti>
        <nome>farina</nome>
        <quantita>3</quantita>
        <unita>3</unita>
    </ingredienti>
    <procedura>
        <procedo>verso la farina</procedo>
        <procedo>inserire l acqua</procedo>
        <procedo>prendere la prima unita </procedo>
        <procedo>mescolare</procedo>
    </procedura>
</ricetta>
<ricetta>
    <titolo>Torta</titolo>
    <autore>Giacomini Giacomo</autore>
    <ingredienti>
        <nome>farina</nome>
        <quantita>3</quantita>
        <unita>3</unita>
    </ingredienti>
    <procedura>
        <procedo>verso la farina</procedo>
        <procedo>inserire l acqua</procedo>
        <procedo>prendere la prima unita </procedo>
        <procedo>mescolare</procedo>
    </procedura>
</ricetta>
<ricetta>
    <titolo>Torta</titolo>
    <autore>Giacomini Giacomo</autore>
    <ingredienti>
        <nome>farina</nome>
        <quantita>3</quantita>
        <unita>3</unita>
    </ingredienti>
    <procedura>
        <procedo>verso la farina</procedo>
        <procedo>inserire l acqua</procedo>
        <procedo>prendere la prima unita </procedo>
        <procedo>mescolare</procedo>
    </procedura>
</ricetta>
</ricettario>
