=== priamixdj/5AI/TPSIT/XML/dtd/siti.dtd
lista[
    <!ELEMENT lista (sito+)>
    <!ELEMENT sito (nome, URL, descrizione, categoria)>
    <!ELEMENT nome (#PCDATA)>
    <!ELEMENT URL (#PCDATA)>
    <!ELEMENT descrizione (#PCDATA)>
    <!ELEMENT categoria (#PCDATA)>
    <!ATTLIST sito IDSito ID #REQUIRED>
]>

=== priamixdj/5AI/TPSIT/XML/dtd/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista SYSTEM "siti.dtd">
<lista>
<sito IDSito="s001">
<nome>CERN</nome>
<URL>http://home.cern/</URL>
<descrizione>Centro europeo per la ricerca nucleare</descrizione>
<categoria>siti istituzionali</categoria>
</sito>
<sito IDSito="s002">
<nome>Museo della scienza e della tecnologia</nome>
<URL>http://www.museoscienza.org/</URL>
<descrizione>Museo Leonardo da Vinci di Milano</descrizione>
<categoria>musei</categoria>
</sito>
</lista>
