=== priamixdj/5AI/TPSIT/XML/fenomeni/fenomeni.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="fenomeni">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="rilevazione" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mese" type="xs:string" />
                            <xs:element name="giorno" type="xs:decimal" />
                            <xs:element name="ora" type="xs:decimal" />
                            <xs:element name="langitudine" type="xs:string" />
                            <xs:element name="longitudine" type="xs:string" />
                            <xs:element name="magnitudo" type="xs:decimal" />
                            <xs:element name="profondita" type="xs:decimal" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== priamixdj/5AI/TPSIT/XML/fenomeni/fenomeni.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<fenomeni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fenomeni.xsd">
    <rilevazione>
        <mese>gennaio</mese>
        <giorno>23</giorno>
        <ora>3</ora>
        <langitudine>+</langitudine>
        <longitudine>-</longitudine>
        <magnitudo>3</magnitudo>
        <profondita>30</profondita>
    </rilevazione>
    <rilevazione>
        <mese>gennaio</mese>
        <giorno>3</giorno>
        <ora>15</ora>
        <langitudine>-</langitudine>
        <longitudine>-</longitudine>
        <magnitudo>5</magnitudo>
        <profondita>30</profondita>
    </rilevazione>
    <rilevazione>
        <mese>maggio</mese>
        <giorno>2</giorno>
        <ora>8</ora>
        <langitudine>+</langitudine>
        <longitudine>-</longitudine>
        <magnitudo>3</magnitudo>
        <profondita>9</profondita>
    </rilevazione>
    <rilevazione>
        <mese>febbraio</mese>
        <giorno>23</giorno>
        <ora>4</ora>
        <langitudine>+</langitudine>
        <longitudine>-</longitudine>
        <magnitudo>3</magnitudo>
        <profondita>5</profondita>
    </rilevazione>
    
</fenomeni>
